language: node_js
node_js:
- stable
sudo: false
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
cache:
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: efbab2889b2194dada09a27dfd612a54da990d09873bedbd75f0be4e2417b571
deploy:
  on:
    tags: true
  email: koike.takayuki0907@gmail.com
  provider: npm
  api_key:
    secure: JKTuBxVSt2xofsWd9lbFfb+z08WjKfaZ1FWCrw+pPZb5Ceb6lOPBMSS4D7UUiHemRC0X++og6LuSlAx3neV6Y+4hKZmK1PxfPYCZg3NY8UG2H4SD+Brf4JMG61rDM3Tjcz0XTPBPGaka3Hjof99VREkrhQ/kxLPeTSj2lxQEwlMxj7BcDPcapVnyCUQd4p2L45aYa37I/Y9UNrh7/O9I9fiTEfEWhTzR17fPedY6OWJ7Zwgb9fzsdnmHTZ8BRqkpI6mXp8OWdgb3wrMY8+xbbO4EwZZRHAzNO/Tjcb9SHGKhJUmxc3NwwtWXHWPjD1UTOq7rcUq9KDysACFJuseH4XBzbqg+BVcSrzgXFSEcMcWxVYo6DSurMmsOnotGUTD6XVDhTAszN+wAEbppB4IzRzfsW6h+76HyfUBJIZQ24ULaTZa9ML96JCNAvFUHhVJy9hIYL+4iOiQbACIF+OjvvYuhDjPt9YWseA/l9vRu8ZE3jKpwtSCeS2QmrMtRsvKjnaMJxm4nXprM2cuwNHjt6gm4UPVG8g5RL1M8S1i3N670lV6EUMv8raadkAzIPMKxH40m0hdnTfj4slLXfAbQOFiX3dpyt3q7jI/DK7U8j5aUa/D+bAAHR/sMXsJp7GffrVjeXxA4Elbxw+q49azl44ni40PavFjwZPJ/IotI5zI=
script:
- npm run build